### DISCUSSION TITLE
Межсервисное взаимодействие

### DISCUSSION THREAD

**Discussion by belousoveu** [SP-Java-IND-30-0/cherkizon-online#70] [General]
### **Правила взаимодействия между микросервисами (REST + Kafka)**  
*(Общая памятка для команды)*  

---

### **1.1. Назначение портов**  
Каждый сервис работает на фиксированном порту в dev-среде:  

| Сервис           | Порт  | Базовый URL               |  
|------------------|-------|---------------------------|  
| **Аутентификация** | 8081  | `http://localhost:8081`    |  
| **Профиль**       | 8082  | `http://localhost:8082`    |  
| **Объявления**    | 8083  | `http://localhost:8083`    |  
| **Комментарии**   | 8084  | `http://localhost:8084`    |  
| **Уведомления**   | 8085  | `http://localhost:8085`    |  

**Важно:**  
- Порт прописывается в `application.yml` сервиса:  
  ```yaml
  server:
    port: 808X  # Зависит от сервиса
  ```

---

### **2.1. Внутренние эндпоинты**  
- Все эндпоинты для межсервисного общения должны быть доступны по пути `/internal/**`.  
- Пример:  
  - `GET /internal/users/{id}` (получение данных пользователя).  
  - `POST /internal/ads/validate` (проверка объявления).  

#### **Зависимости**  
Добавить в `pom.xml`:  
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-openfeign</artifactId>
</dependency>
```

#### **Конфигурация в `application.yml`**  
```yaml
spring:
  cloud:
    openfeign:
      client:
        config:
          default:  # Настройки по умолчанию
            connect-timeout: 5000  # 5 сек
            read-timeout: 5000     # 5 сек
            logger-level: basic    # Логирование
          profile-service:  # Конкретный клиент
            url: http://localhost:8082
```

#### **Пример Feign-клиента**  
```java
@FeignClient(name = "profile-service", path = "/internal/users")
public interface ProfileServiceClient {
    @GetMapping("/{userId}")
    ResponseEntity<UserProfileResponse> getUserById(@PathVariable Long userId);
}
```

#### **Использование в сервисе**  
```java
@Service
@RequiredArgsConstructor
public class AdService {
    private final ProfileServiceClient profileClient;

    public Ad createAd(CreateAdRequest request, Long userId) {
        UserProfileResponse user = profileClient.getUserById(userId);
        // ...
    }
}
```

---

### **3.1. Именование топиков**  
Формат: **`domain.object.action`** (через точку).  
Примеры:  
- `user.profile.created`  
- `ad.comment.deleted`  
- `notification.email.sent`  

### **3.2. Отправка событий**  
```java
kafkaTemplate.send("ad.comment.created", new CommentEvent(...));
```

### **3.3. Обработка событий**  
```java
@KafkaListener(topics = "ad.comment.created")
public void handleCommentCreated(CommentEvent event) {
    // Логика обработки
}
```

---

### **4.1. Feign Fallback**  
```java
@FeignClient(
    name = "profile-service",
    fallback = ProfileServiceClientFallback.class
)
public interface ProfileServiceClient { ... }

@Component
public class ProfileServiceClientFallback implements ProfileServiceClient {
    @Override
    public ResponseEntity<UserProfileResponse> getUserById(Long userId) {
        return ResponseEntity.status(503).build();
    }
}
```

### **4.2. Retry для Feign**  
Добавить в `application.yml`:  
```yaml
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            retry:
              max-attempts: 3  # 3 попытки
              backoff:
                delay: 1000     # Задержка 1 сек
```

### **Схема взаимодействия**  
- Синхронные запросы (REST)
```
[Сервис A] --(Feign)--> [Сервис B]
```
- Асинхронные события (Kafka)
```
[Сервис A] --(Kafka)--> [Сервис B]
```

## Формат запроса эндройнта
Запрос на создание нужного эндпойнта в другом сервисе оставляйте в комментариях к этому посту в следующем формате (пример)

**1. Контекст:**
Нам в сервисе Комментарии нужен доступ к данным объявления (заголовок, автор) для отображения в интерфейсе.

**2. Требуемый эндпоинт:**

Метод: GET

Путь: `/internal/ads/{adId}/summary`
Ответ:

```
{
  "adId": 123,
  "title": "Продам велосипед",
  "author": {
    "firstName": "Иван",
    "lastName": "Петров"
  }
}
```
**3. Ожидаемые сценарии:**

`200 OK` – объявление найдено.

`404 Not Found` – объявление не существует.
